language: objective-c
osx_image: xcode8.2

before_install:
  - gem install xcpretty

  # Install dependent pods during Travis integration. Updates the CocoaPods repo
  # first. Installing does not update the repo by default.
  - pod install --repo-update

env:
  matrix:
    # Travis has multiple SDK destinations matching by name and OS; use the
    # destination ID to resolve the iOS Simulator, iOS 10.2, iPhone SE platform
    # uniquely.
    - DESTINATION="id=DB794781-65A7-4884-8D00-AAC3CBD39A44"

script:
  - xcodebuild -sdk "$TRAVIS_XCODE_SDK" -workspace "$TRAVIS_XCODE_WORKSPACE.xcworkspace" -scheme "$TRAVIS_XCODE_SCHEME" -destination "$DESTINATION" test | xcpretty && exit ${PIPESTATUS[0]}

# Important to specify the simulator SDK, otherwise Travis CI will attempt to
# build for the real iPhone and fail due to code-signing issues.
# See https://docs.travis-ci.com/user/languages/objective-c for details.
xcode_sdk: iphonesimulator10.2

xcode_scheme: FaradayHAL

xcode_workspace: FaradayHAL
